# Конфигурация golangci-lint
# Это как "правила проверки" для твоего кода

run:
  timeout: 5m  # Максимальное время работы
  tests: false  # Не проверять тестовые файлы так строго

# Какие линтеры включить?
linters:
  enable:
    - gofmt         # Проверка форматирования
    - govet         # Поиск подозрительных конструкций
    - errcheck      # Проверка обработки ошибок
    - staticcheck   # Множество проверок
    - unused        # Неиспользуемый код
    - gosimple      # Упрощение кода
    - ineffassign   # Неэффективные присваивания
    - typecheck     # Проверка типов
    - misspell      # Опечатки в комментариях
    - gocyclo       # Сложность функций
    # - dupl        # Дублирование кода (отключено - для pet project OK)
    - gosec         # Security issues

# Настройки для конкретных линтеров
linters-settings:
  gocyclo:
    min-complexity: 15  # Максимальная сложность функции
  
  dupl:
    threshold: 100  # Минимум строк для определения дубликата
  
  errcheck:
    check-blank: false  # Разрешить игнорировать ошибки через _

# Какие файлы/папки пропустить?
issues:
  exclude-rules:
    # Разрешить длинные строки в тестах
    - path: _test\.go
      linters:
        - lll
    
    # Игнорировать некоторые ошибки в vendor
    - path: vendor/
      linters:
        - all
  
  # Не показывать эти конкретные ошибки
  exclude:
    - "G104: Errors unhandled"  # Иногда можно игнорировать ошибки
    - "Error return value of `a.sendResponse` is not checked"  # В panic handler это OK
    
  max-same-issues: 0  # Показывать все найденные проблемы
