// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package agent

import (
	"context"
	"github.com/godofphonk/ServerEye/internal/config"
	"github.com/godofphonk/ServerEye/internal/interfaces"
	"github.com/godofphonk/ServerEye/pkg/commands"
	"github.com/godofphonk/ServerEye/pkg/docker"
	"github.com/godofphonk/ServerEye/pkg/metrics"
	"github.com/godofphonk/ServerEye/pkg/websocket"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
	"time"
)

// Injectors from wire.go:

// InitializeAgent creates a new agent with dependency injection
func InitializeAgent(ctx context.Context, configPath string) (*Agent, error) {
	configService, err := provideConfig(configPath)
	if err != nil {
		return nil, err
	}
	logger := provideLogger()
	metricsCollector := provideMetricsCollector()
	systemMonitor := provideSystemMonitor(logger)
	dockerManager := provideDockerManager(logger)
	agentConfig, err := provideAgentConfig(configPath, configService)
	if err != nil {
		return nil, err
	}
	client := provideWebSocketClient(agentConfig, logger)
	metricsPublisher := provideMetricsPublisher(agentConfig, client, logger)
	commandConsumer := provideCommandConsumer(agentConfig, client, logger)
	agent, err := provideAgent(ctx, configPath, configService, logger, metricsCollector, systemMonitor, dockerManager, metricsPublisher, commandConsumer)
	if err != nil {
		return nil, err
	}
	return agent, nil
}

// wire.go:

// ProviderSet is a collection of providers for the agent package
var ProviderSet = wire.NewSet(
	provideLogger,
	provideConfig,
	provideAgentConfig,
	provideWebSocketClient,
	provideMetricsCollector,
	provideSystemMonitor,
	provideDockerManager,
	provideMetricsPublisher,
	provideCommandConsumer,
	provideAgent,
)

// provideLogger creates a new logger instance
func provideLogger() interfaces.Logger {
	logger := logrus.New()
	logger.SetFormatter(&logrus.TextFormatter{
		FullTimestamp: true,
		ForceColors:   true,
	})
	return interfaces.NewLogrusAdapter(logger)
}

// provideConfig creates a new config service
func provideConfig(configPath string) (*config.ConfigService, error) {
	return config.NewConfigService(), nil
}

// provideAgentConfig creates a new agent config
func provideAgentConfig(configPath string, configService *config.ConfigService) (*config.AgentConfig, error) {
	return configService.LoadAgentConfig(configPath)
}

// provideWebSocketClient creates a new WebSocket client
func provideWebSocketClient(cfg *config.AgentConfig, logger interfaces.Logger) *websocket.Client {

	logrusLogger := logger.(*interfaces.LogrusAdapter).Entry.Logger

	wsURL := cfg.WebSocket.URL
	if wsURL == "" {

		wsURL = "ws" + cfg.API.BaseURL[4:] + "/ws"
	}

	reconnectInterval := parseDuration(cfg.WebSocket.ReconnectInterval, 5*time.Second)
	maxReconnectAttempts := cfg.WebSocket.MaxReconnectAttempts
	if maxReconnectAttempts == 0 {
		maxReconnectAttempts = 10
	}
	pingInterval := parseDuration(cfg.WebSocket.PingInterval, 30*time.Second)
	writeTimeout := parseDuration(cfg.WebSocket.WriteTimeout, 10*time.Second)
	readTimeout := parseDuration(cfg.WebSocket.ReadTimeout, 10*time.Second)
	handshakeTimeout := parseDuration(cfg.WebSocket.HandshakeTimeout, 10*time.Second)
	bufferSize := cfg.WebSocket.BufferSize
	if bufferSize == 0 {
		bufferSize = 1000
	}

	wsConfig := websocket.Config{
		URL:                  wsURL,
		ServerID:             cfg.Server.ServerID,
		ServerKey:            cfg.Server.SecretKey,
		ReconnectInterval:    reconnectInterval,
		MaxReconnectAttempts: maxReconnectAttempts,
		PingInterval:         pingInterval,
		WriteTimeout:         writeTimeout,
		ReadTimeout:          readTimeout,
		HandshakeTimeout:     handshakeTimeout,
		BufferSize:           bufferSize,
		EnableCompression:    cfg.WebSocket.EnableCompression,
		APIURL:               cfg.API.BaseURL,
		APIKey:               cfg.API.APIKey,
	}

	return websocket.NewClient(wsConfig, logrusLogger)
}

// provideMetricsCollector creates a new metrics collector
func provideMetricsCollector() interfaces.MetricsCollector {
	return metrics.NewCPUMetrics()
}

// provideSystemMonitor creates a new system monitor
func provideSystemMonitor(logger interfaces.Logger) interfaces.SystemMonitor {

	logrusLogger := logger.(*interfaces.LogrusAdapter).Entry.Logger
	monitor := metrics.NewSystemMonitor(logrusLogger)
	return interfaces.NewSystemMonitorAdapter(monitor)
}

// provideDockerManager creates a new Docker manager
func provideDockerManager(logger interfaces.Logger) interfaces.DockerManager {

	logrusLogger := logger.(*interfaces.LogrusAdapter).Entry.Logger
	client := docker.NewClient(logrusLogger)
	return interfaces.NewDockerManagerAdapter(client)
}

// provideMetricsPublisher creates a new metrics publisher
func provideMetricsPublisher(cfg *config.AgentConfig, wsClient *websocket.Client, logger interfaces.Logger) interfaces.MetricsPublisher {

	logrusLogger := logger.(*interfaces.LogrusAdapter).Entry.Logger

	wsURL := cfg.WebSocket.URL
	if wsURL == "" {

		wsURL = "ws" + cfg.API.BaseURL[4:] + "/ws"
	}

	reconnectInterval := parseDuration(cfg.WebSocket.ReconnectInterval, 5*time.Second)
	maxReconnectAttempts := cfg.WebSocket.MaxReconnectAttempts
	if maxReconnectAttempts == 0 {
		maxReconnectAttempts = 10
	}
	pingInterval := parseDuration(cfg.WebSocket.PingInterval, 30*time.Second)
	writeTimeout := parseDuration(cfg.WebSocket.WriteTimeout, 10*time.Second)
	readTimeout := parseDuration(cfg.WebSocket.ReadTimeout, 10*time.Second)
	handshakeTimeout := parseDuration(cfg.WebSocket.HandshakeTimeout, 10*time.Second)
	bufferSize := cfg.WebSocket.BufferSize
	if bufferSize == 0 {
		bufferSize = 1000
	}
	metricBufferSize := cfg.WebSocket.MetricBufferSize
	if metricBufferSize == 0 {
		metricBufferSize = 100
	}
	metricBufferFlush := parseDuration(cfg.WebSocket.MetricBufferFlush, 30*time.Second)

	metricsConfig := metrics.Config{
		URL:                  wsURL,
		ServerID:             cfg.Server.ServerID,
		ServerKey:            cfg.Server.SecretKey,
		ReconnectInterval:    reconnectInterval,
		MaxReconnectAttempts: maxReconnectAttempts,
		PingInterval:         pingInterval,
		WriteTimeout:         writeTimeout,
		ReadTimeout:          readTimeout,
		HandshakeTimeout:     handshakeTimeout,
		BufferSize:           bufferSize,
		EnableCompression:    cfg.WebSocket.EnableCompression,
		MetricBufferSize:     metricBufferSize,
		MetricBufferFlush:    metricBufferFlush,
		APIURL:               cfg.API.BaseURL,
		APIKey:               cfg.API.APIKey,
	}

	return metrics.NewWebSocketPublisher(metricsConfig, logrusLogger)
}

// provideCommandConsumer creates a new command consumer
func provideCommandConsumer(cfg *config.AgentConfig, wsClient *websocket.Client, logger interfaces.Logger) interfaces.CommandConsumer {

	logrusLogger := logger.(*interfaces.LogrusAdapter).Entry.Logger

	wsURL := cfg.WebSocket.URL
	if wsURL == "" {

		wsURL = "ws" + cfg.API.BaseURL[4:] + "/ws"
	}

	reconnectInterval := parseDuration(cfg.WebSocket.ReconnectInterval, 5*time.Second)
	maxReconnectAttempts := cfg.WebSocket.MaxReconnectAttempts
	if maxReconnectAttempts == 0 {
		maxReconnectAttempts = 10
	}
	pingInterval := parseDuration(cfg.WebSocket.PingInterval, 30*time.Second)
	writeTimeout := parseDuration(cfg.WebSocket.WriteTimeout, 10*time.Second)
	readTimeout := parseDuration(cfg.WebSocket.ReadTimeout, 10*time.Second)
	handshakeTimeout := parseDuration(cfg.WebSocket.HandshakeTimeout, 10*time.Second)
	bufferSize := cfg.WebSocket.BufferSize
	if bufferSize == 0 {
		bufferSize = 1000
	}
	commandQueueSize := cfg.WebSocket.CommandQueueSize
	if commandQueueSize == 0 {
		commandQueueSize = 100
	}
	commandTimeout := parseDuration(cfg.WebSocket.CommandTimeout, 30*time.Second)

	commandsConfig := commands.Config{
		URL:                  wsURL,
		ServerID:             cfg.Server.ServerID,
		ServerKey:            cfg.Server.SecretKey,
		ReconnectInterval:    reconnectInterval,
		MaxReconnectAttempts: maxReconnectAttempts,
		PingInterval:         pingInterval,
		WriteTimeout:         writeTimeout,
		ReadTimeout:          readTimeout,
		HandshakeTimeout:     handshakeTimeout,
		BufferSize:           bufferSize,
		EnableCompression:    cfg.WebSocket.EnableCompression,
		CommandQueueSize:     commandQueueSize,
		CommandTimeout:       commandTimeout,
		APIURL:               cfg.API.BaseURL,
		APIKey:               cfg.API.APIKey,
	}

	consumer := commands.NewWebSocketCommandConsumer(commandsConfig, nil, logrusLogger)
	return consumer
}

// provideAgent creates a new agent with all dependencies
func provideAgent(
	ctx context.Context,
	configPath string,
	configService *config.ConfigService,
	logger interfaces.Logger,
	metricsCollector interfaces.MetricsCollector,
	systemMonitor interfaces.SystemMonitor,
	dockerManager interfaces.DockerManager,
	metricsPublisher interfaces.MetricsPublisher,
	commandConsumer interfaces.CommandConsumer,
) (*Agent, error) {

	cfg, err := configService.LoadAgentConfig(configPath)
	if err != nil {
		return nil, err
	}

	logrusLogger := logger.(*interfaces.LogrusAdapter).Entry.Logger

	agent := &Agent{
		config:            cfg,
		logger:            interfaces.NewLogrusAdapter(logrusLogger),
		wsPublisher:       metricsPublisher,
		wsCommandConsumer: commandConsumer,
		useWebSocket:      cfg.WebSocket.Enabled,
		cpuMetrics:        metricsCollector,
		systemMonitor:     systemMonitor,
		dockerClient:      dockerManager,
		startTime:         time.Now(),
	}

	agent.ctx, agent.cancel = context.WithCancel(ctx)

	return agent, nil
}
